# Generated by Django 4.1.7 on 2023-04-18 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50)),
                ('burned_calories', models.IntegerField()),
                ('runtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('calories', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('water', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.activity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sex', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=6)),
                ('purpose', models.CharField(choices=[('LOSS', 'Похудение'), ('INCREASE', 'Набор веса'), ('MAINTENANCE', 'Поддержание веса')], max_length=11)),
                ('activity_level', models.CharField(choices=[('LOW', 'Низкий'), ('MIDDLE', 'Умеренный'), ('HIGH', 'Высокий'), ('INTENSIVE', 'Интенсивный')], max_length=9)),
                ('activity', models.ManyToManyField(through='users.Reports', to='users.activity')),
                ('product', models.ManyToManyField(through='users.Reports', to='users.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightChange',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('bmi', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdata')),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdata'),
        ),
    ]
